const data = {
  homePage: [
    {
      uniqueId: "1",
      backgroundImage: "../assets/home_BackgroundPage.jpeg",
    },
  ],
  aboutPage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/about_BackgroundPage.webp",
    },
  ],
  servisePage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/servise_backgroundPage.jpeg",
    },
  ],
  projectPage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/project_backgroundPage.jpeg",
    },
  ],
  talkToUsPage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/contact_BackgroundPage.jpeg",
    },
  ],
  services: [
    {
      _id: "1",
      slag: "11",
      name: "Web Development",
      category: "Shirts",
      image:
        "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-125302913.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "We are an Erbil web design company delivering stunning, functional websites and web-apps that resonate with the people interacting with them – your clients. Our websites and web-apps don't just look good, they perform, they convert. If you are looking to generate enquiries, increase sales or maximise awareness we have the in-house web design and development teams in place to achieve this. Suncode IT Solutions and Consultancy is a dependable Erbil Web Development partner in the area, Iraq who purposefully tailors our services to meet the specific needs of agencies. We know you want a trouble-free development experience and a site that functions exactly as designed. We provide reliable maintenance services that release you from the burden of managing upgrades and handling unplanned client support tasks. Our agency clients handle the digital strategy, creative design and overall project direction. We take care of the development and ongoing support. Smart Solutions can come to the table as your development team or work invisibly to support your brand.",
    },
    {
      _id: "2",
      slag: "12",
      name: "Graphic Design",
      category: "Shirts",
      // image: "./images/web_design.jpeg",
      image:
        "https://media.istockphoto.com/photos/web-designer-working-with-multiple-devices-picture-id1334906074?b=1&k=20&m=1334906074&s=170667a&w=0&h=l6Zv77OswP1-mcD0jzdqy48pd7PjlJmTfkUKga7xIoo=",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "We are an Erbil web design company delivering stunning, functional websites and web-apps that resonate with the people interacting with them – your clients. Our websites and web-apps don't just look good, they perform, they convert. If you are looking to generate enquiries, increase sales or maximise awareness we have the in-house web design and development teams in place to achieve this. Suncode IT Solutions and Consultancy is a dependable Erbil Web Development partner in the area, Iraq who purposefully tailors our services to meet the specific needs of agencies. We know you want a trouble-free development experience and a site that functions exactly as designed. We provide reliable maintenance services that release you from the burden of managing upgrades and handling unplanned client support tasks. Our agency clients handle the digital strategy, creative design and overall project direction. We take care of the development and ongoing support. Smart Solutions can come to the table as your development team or work invisibly to support your brand.",
    },
    {
      _id: "3",
      slag: "13",
      name: "Web Hosting",
      category: "Shirts",
      image:
        "https://www.dreamhost.com/academy/wp-content/uploads/2020/12/what-is-web-hosting.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "We are an Erbil web design company delivering stunning, functional websites and web-apps that resonate with the people interacting with them – your clients. Our websites and web-apps don't just look good, they perform, they convert. If you are looking to generate enquiries, increase sales or maximise awareness we have the in-house web design and development teams in place to achieve this. Suncode IT Solutions and Consultancy is a dependable Erbil Web Development partner in the area, Iraq who purposefully tailors our services to meet the specific needs of agencies. We know you want a trouble-free development experience and a site that functions exactly as designed. We provide reliable maintenance services that release you from the burden of managing upgrades and handling unplanned client support tasks. Our agency clients handle the digital strategy, creative design and overall project direction. We take care of the development and ongoing support. Smart Solutions can come to the table as your development team or work invisibly to support your brand.",
    },
    {
      _id: "4",
      slag: "14",
      name: "Consulting",
      category: "Shirts",
      image:
        "https://thumbs.dreamstime.com/b/business-consulting-concept-virtual-screen-business-consulting-concept-virtual-screen-153994074.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "We are an Erbil web design company delivering stunning, functional websites and web-apps that resonate with the people interacting with them – your clients. Our websites and web-apps don't just look good, they perform, they convert. If you are looking to generate enquiries, increase sales or maximise awareness we have the in-house web design and development teams in place to achieve this. Suncode IT Solutions and Consultancy is a dependable Erbil Web Development partner in the area, Iraq who purposefully tailors our services to meet the specific needs of agencies. We know you want a trouble-free development experience and a site that functions exactly as designed. We provide reliable maintenance services that release you from the burden of managing upgrades and handling unplanned client support tasks. Our agency clients handle the digital strategy, creative design and overall project direction. We take care of the development and ongoing support. Smart Solutions can come to the table as your development team or work invisibly to support your brand.",
    },
  ],

  products: [
    {
      _id: "1",
      slag: "11",
      name: "Nike Slim Shirt ",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "2",
      slag: "22",
      name: "Adidas Fit Shirt ",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "3",
      slag: "33",
      name: "Lacoste Free Shirt ",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },

    {
      _id: "4",
      slag: "44",
      name: "Nika Slim Pant",
      category: "Pants",
      image: "./images/p1.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },

    {
      _id: "5",
      slag: "55",
      name: "Puma Slim Pants",
      category: "Pant",
      image: "./images/p1.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "6",
      slag: "66",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "./images/p1.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
  categories: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};

export default data;
